import type {
  GenerateContentInput,
  GenerateContentOutput,
  LlmAdapter,
} from "@/server/adapters/llm/types";

function buildMockTitle(input: GenerateContentInput): string | undefined {
  const topicTitle =
    typeof input.context.topicTitle === "string"
      ? input.context.topicTitle
      : typeof input.context.baseTitle === "string"
        ? input.context.baseTitle
        : undefined;

  if (!topicTitle) {
    return undefined;
  }

  if (input.taskType === "GENERATE_MASTER") {
    return `${topicTitle}｜母稿`;
  }

  if (input.taskType === "REWRITE") {
    const strategy = typeof input.context.strategy === "string" ? input.context.strategy : "MIXED";
    return `${topicTitle}｜${strategy} 改写`;
  }

  const channel = typeof input.context.channel === "string" ? input.context.channel : "CHANNEL";
  return `${topicTitle}｜${channel} 包装`;
}

export const mockLlmAdapter: LlmAdapter = {
  async generate(input: GenerateContentInput): Promise<GenerateContentOutput> {
    const title = buildMockTitle(input);
    const summary =
      input.taskType === "PACKAGE_CHANNEL"
        ? "Mock packaging summary."
        : input.taskType === "REWRITE"
          ? "Mock rewrite summary."
          : "Mock master draft summary.";

    return {
      title,
      summary,
      content: `# ${title ?? "Content"}\n\n${input.prompt}\n\nThis content is generated by the mock LLM adapter.`,
      metadata: {
        provider: "mock",
        model: input.model ?? "mock-model",
      },
    };
  },
};
